stages:
  - test
  - build

test:
  stage: test
  image: microsoft/dotnet:2.0-sdk

  before_script:
    - dotnet restore

  script:
    - dotnet test Protogen.Tests

build:
  stage: build
  image: microsoft/dotnet:2.0-sdk

  only:
    - tags
    - master

  before_script:
    - "sed -ri 's/([[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+)<\\/Version>/'${CI_COMMIT_TAG:-\"\\\\1-build-${CI_JOB_ID}\"}'<\\/Version>/' Protogen/Protogen.csproj"
    - "sed -ri 's/([[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+)<\\/Version>/'${CI_COMMIT_TAG:-\"\\\\1-build-${CI_JOB_ID}\"}'<\\/Version>/' Protogen.Models/Protogen.Models.csproj"
    - dotnet restore

  script:
    - dotnet build -c Release Protogen.Models
    - dotnet build -c Release Protogen
    - dotnet nuget push `find Protogen.Models -name "*.nupkg"` -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY
    - dotnet nuget push `find Protogen -name "*.nupkg"` -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY