stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: microsoft/dotnet:2.0-sdk

  before_script:
    - dotnet restore

  script:
    - dotnet test Protogen.Tests

build:
  stage: build
  image: microsoft/dotnet:2.0-sdk

  before_script:
    - dotnet restore

  script:
    - dotnet build -c Release -p Protogen.Models
    - dotnet build -c Release -p Protogen
  
  artifacts:
    expire_in: 12 hrs
    paths:
      - Protogen/bin/Release/netcoreapp2.0/Protogen.Tools.*.nupkg
      - Protogen.Models/bin/Release/netcoreapp2.0/Protogen.Models.*.nupkg

deploy:
  stage: deploy
  image: microsoft/dotnet:2.0-sdk

  only:
    - tags
  
  dependencies:
    - build

  script:
    - dotnet nuget push Protogen.Models/bin/Release/netcoreapp2.0/Protogen.Models.*.nupkg -k $NUGET_API_KEY
    - dotnet nuget push Protogen/bin/Release/netcoreapp2.0/Protogen.Tools.*.nupkg -k $NUGET_API_KEY