/// <auto-generated>
/// This file was automatically generated using Protogen.
/// </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using System.Linq;

namespace SimpleExample.Models
{
    /// <summary>
    /// EntityFramework DbContext subclass for SimpleExample
    /// </summary>
    public partial class SimpleExampleDbContext : DbContext
    {
        /// <summary>
        /// Gets or sets the collection of <see cref="Todo"/>
        /// </summary>
        public DbSet<Todo> Todos { get; set; }

        
        /// <summary>
        /// Overrides to add complex keys and other features. Calls the superclasses OnModelCreating.
        /// </summary>
        /// <param name="modelBuilder">The model builder being created.</param>
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
        }
    }
}
