/// <auto-generated>
/// This file was automatically generated using Protogen.
/// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SimpleExample.Models
{
    /// <summary>
    /// A task that can be marked as completed.
    /// </summary>
    [Table("todos")]
    public partial class Todo
    {
        /// <summary>
        /// Gets or sets The unqiue ID of the task
        /// /summary>
        [Key]
        [Required]
        [Column("id")]
        public long Id { get; set; }

        /// <summary>
        /// Gets or sets 
        /// /summary>
        [Column("completed_at")]
        public DateTimeOffset? CompletedAt { get; set; }

        /// <summary>
        /// Gets or sets 
        /// /summary>
        [Column("parent_id")]
        public long? ParentId { get; set; }

        /// <summary>
        /// Gets or sets 
        /// /summary>
        [ForeignKey(nameof(ParentId))]
        public virtual Todo Parent { get; set; }

        /// <summary>
        /// Gets or sets 
        /// /summary>
        [Required]
        [Column("priority")]
        public bool Priority { get; set; }

        /// <summary>
        /// Gets or sets 
        /// /summary>
        [Required]
        [Column("task")]
        public string Task { get; set; }

        /// <summary>
        /// Gets or sets the inverse-related list of <see cref="Todo"/>
        /// /summary>
        [InverseProperty(nameof(Parent))]
        public virtual ICollection<Todo> Children { get; set; }
    }
}
