/// <auto-generated>
/// This file was automatically generated using Protogen.
/// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CompoundKey.Models
{
    /// <summary>
    /// 
    /// </summary>
    [Table("store_products")]
    public partial class StoreProduct
    {
        /// <summary>
        /// Gets or sets 
        /// /summary>
        [Required]
        [Column("product_id")]
        public long ProductId { get; set; }

        /// <summary>
        /// Gets or sets 
        /// /summary>
        [ForeignKey(nameof(ProductId))]
        public virtual Product Product { get; set; }

        /// <summary>
        /// Gets or sets 
        /// /summary>
        [Required]
        [Column("store_id")]
        public long StoreId { get; set; }

        /// <summary>
        /// Gets or sets 
        /// /summary>
        [ForeignKey(nameof(StoreId))]
        public virtual Store Store { get; set; }

        /// <summary>
        /// Gets or sets 
        /// /summary>
        [Required]
        [Column("price")]
        public double Price { get; set; }
    }
}
