/// <auto-generated>
/// This file was automatically generated using Protogen.
/// </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CompoundKey.Models
{
    /// <summary>
    /// 
    /// </summary>
    [Table("stores")]
    public partial class Store
    {
        /// <summary>
        /// Gets or sets 
        /// /summary>
        [Key]
        [Required]
        [Column("id")]
        public long Id { get; set; }

        /// <summary>
        /// Gets or sets 
        /// /summary>
        [Required]
        [Column("name")]
        public string Name { get; set; }
    }
}
