/// <auto-generated>
/// This file was automatically generated using Protogen.
/// </auto-generated>
using System;
using GraphQL;
using GraphQL.Types;

namespace SimpleExample.GraphQL
{
    /// <summary>
    /// Defines the GraphQL interface for queries.
    /// </summary>
    public abstract class SimpleExampleQueryBase : ObjectGraphType
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SimpleExampleQueryBase"/> class.
        /// </summary>
        public SimpleExampleQueryBase()
        {
            Field<TodoType>(
                "allTodos",
                resolve: ResolveAllTodos,
                description: @"",
                arguments: new QueryArguments(
                    new QueryArgument(typeof(int).GetGraphTypeFromType(true))
                    {
                        Name = "offset",
                        DefaultValue = 0,
                        Description = @"The offset to start the query at"
                    },
                    new QueryArgument(typeof(int).GetGraphTypeFromType(true))
                    {
                        Name = "limit",
                        DefaultValue = 50,
                        Description = @"The number of rows to return"
                    }
                )
            );
        }

        /// <summary>
        /// Resolves the result of this query
        /// </summary>
        /// <param name="context">The context of the query</param>
        /// <returns>The result</returns>
        public abstract object ResolveAllTodos(ResolveFieldContext<object> context);
    }
}
