/// <auto-generated>
/// This file was automatically generated using Protogen.
/// </auto-generated>
using System;
using GraphQL;
using GraphQL.Types;

namespace CompoundKey.GraphQL
{
    /// <summary>
    /// Defines the GraphQL interface for queries.
    /// </summary>
    public abstract class CompoundKeyQueryBase : ObjectGraphType
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CompoundKeyQueryBase"/> class.
        /// </summary>
        public CompoundKeyQueryBase()
        {
            Field<ProductType>(
                "allProducts",
                resolve: ResolveAllProducts,
                description: @"",
                arguments: new QueryArguments(
                    new QueryArgument(typeof(int).GetGraphTypeFromType(true))
                    {
                        Name = "offset",
                        DefaultValue = 0,
                        Description = @"The offset to start the query at"
                    },
                    new QueryArgument(typeof(int).GetGraphTypeFromType(true))
                    {
                        Name = "limit",
                        DefaultValue = 50,
                        Description = @"The number of rows to return"
                    }
                )
            );
            Field<StoreType>(
                "allStores",
                resolve: ResolveAllStores,
                description: @"",
                arguments: new QueryArguments(
                    new QueryArgument(typeof(int).GetGraphTypeFromType(true))
                    {
                        Name = "offset",
                        DefaultValue = 0,
                        Description = @"The offset to start the query at"
                    },
                    new QueryArgument(typeof(int).GetGraphTypeFromType(true))
                    {
                        Name = "limit",
                        DefaultValue = 50,
                        Description = @"The number of rows to return"
                    }
                )
            );
            Field<StoreProductType>(
                "allStoreProducts",
                resolve: ResolveAllStoreProducts,
                description: @"",
                arguments: new QueryArguments(
                    new QueryArgument(typeof(int).GetGraphTypeFromType(true))
                    {
                        Name = "offset",
                        DefaultValue = 0,
                        Description = @"The offset to start the query at"
                    },
                    new QueryArgument(typeof(int).GetGraphTypeFromType(true))
                    {
                        Name = "limit",
                        DefaultValue = 50,
                        Description = @"The number of rows to return"
                    }
                )
            );
        }

        /// <summary>
        /// Resolves the result of this query
        /// </summary>
        /// <param name="context">The context of the query</param>
        /// <returns>The result</returns>
        public abstract object ResolveAllProducts(ResolveFieldContext<object> context);

        /// <summary>
        /// Resolves the result of this query
        /// </summary>
        /// <param name="context">The context of the query</param>
        /// <returns>The result</returns>
        public abstract object ResolveAllStores(ResolveFieldContext<object> context);

        /// <summary>
        /// Resolves the result of this query
        /// </summary>
        /// <param name="context">The context of the query</param>
        /// <returns>The result</returns>
        public abstract object ResolveAllStoreProducts(ResolveFieldContext<object> context);
    }
}
