/// <auto-generated>
/// This file was automatically generated using Protogen.
/// </auto-generated>
using System;
using System.Linq;
using GraphQL;
using GraphQL.Types;
using CompoundKey.Models;

namespace CompoundKey.GraphQL
{
    /// <summary>
    /// 
    /// </summary>
    public class ProductType : ObjectGraphType<Product>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Product"/> class.
        /// </summary>
        public ProductType()
        {
            Field(
                typeof(long).GetGraphTypeFromType(false),
                "id",
                @"",
                resolve: ctx => ctx.Source.Id
            );
            Field(
                typeof(double).GetGraphTypeFromType(false),
                "msrp",
                @"",
                resolve: ctx => ctx.Source.Msrp
            );
            Field(
                typeof(string).GetGraphTypeFromType(false),
                "name",
                @"",
                resolve: ctx => ctx.Source.Name
            );
        }
    }
}
